FileTemplateManager/Models/AnswerModel.cs
using DAL.Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace FileTemplateManager.Models
{
	public class AnswerModel
	{
		public IEnumerable<Project> Projects { get; set; }

		public Project SelectedProject { get; set; }

		public IEnumerable<Question> Questions { get; set; }
		public HttpPostedFileBase ImageFile { get; set; }
		public Question SelectedQuestion { get; set; }
	}
}

FileTemplateManager/Models/FieldInfo.cs
using Bussiness;
using DAL.Repositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace FileTemplateManager.Models
{
	public class FieldInfo
	{
		public AvaliableFields Field { get; set; }

		public bool IsUsed { get; set; }

	}
}

FileTemplateManager/Models/TemplateModel.cs
using Bussiness;
using DAL.Data;
using DAL.Repositories;
using System;
using System.Collections.Generic;
using System.Linq;

namespace FileTemplateManager.Models
{
	public class TemplateModel
	{
		public TemplateModel() :
			this(
				1,
				selectedFields: new[]
				{
					AvaliableFields.ProjectId,
					AvaliableFields.QuestionId
				},
				separator: Separators.Dash
			)
		{
		}

		public TemplateModel(int projectId, AvaliableFields[] selectedFields, Separators separator)
		{
			SelectedFields = selectedFields.ToList();
			Separator = separator;
			SelectedProjectId = projectId;
		}

		public List<AvaliableFields> SelectedFields { get; set; }

		public List<FieldInfo> Fields
		{
			get
			{
				return Enum.GetValues(typeof(AvaliableFields))
					.Cast<AvaliableFields>()
					.Select(x => new FieldInfo
					{
						Field = x,
						IsUsed = SelectedFields.Contains(x)
					})
					.ToList();
			}
		}

		public Separators Separator { get; set; }

		public string SampleFileName
		{
			get
			{
				string[] selectedFields = SelectedFields
					.Select(f => f.ToString())
					.ToArray();

				string separatorString = (Separator == Separators.Dot)
					? "."
					: "-";
				var result = string.Join(separatorString, selectedFields);

				return result;
			}
		}

		public int SelectedProjectId { get; set; }

		public IEnumerable<Project> Projects { get; set; }
	}

}

FileTemplateManager/Controllers/HomeController.cs
using Bussiness;
using DAL.Data;
using FileTemplateManager.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FileTemplateManager.Controllers
{
	public class HomeController : Controller
	{
		private readonly IProjectService projectService;

		public HomeController(IProjectService projectService)
		{
			this.projectService = projectService;
		}

		public ActionResult Index()
		{
			return View();
		}

		public ActionResult SetAnswer()
		{
			var model = new AnswerModel();
			model.Projects = projectService.GetProjects();
			model.SelectedProject = model.Projects.FirstOrDefault();
			model.Questions = model.SelectedProject.Questions;
			model.SelectedQuestion = model.SelectedProject.Questions.FirstOrDefault();
			return View(model);
		}

		public ActionResult GetQuestions(int projectId)
		{
			var questions = projectService
				.GetProjectById(projectId)
				.Questions
				.Select(x => new
				{
					QuestionId = x.QuestionId,
					Text = x.Text
				});
			return Json(questions, JsonRequestBehavior.AllowGet);
		}
	}
}

FileTemplateManager/Controllers/ManageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FileTemplateManager.Controllers
{
	public class ManageController : Controller
	{
		public ActionResult Index()
		{
			return View();
		}

		[HttpPost]
		public string Save()
		{
			return "Hello world!";
		}
	}
}

FileTemplateManager/Controllers/ManageTemplateController.cs
using Bussiness;
using DAL.Data;
using DAL.Repositories;
using FileTemplateManager.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FileTemplateManager.Controllers
{
	public class ManageTemplateController : Controller
	{
		private readonly IProjectService projectService;

		public ManageTemplateController(IProjectService projectService)
		{
			this.projectService = projectService;
		}

		[HttpGet]
		public ActionResult Setup()
		{
			IEnumerable<Project> projects = projectService.GetProjects();
			Project selectedProject = projects.First();

			var model = GetTempleteModel(selectedProject);
			model.Projects = projects;

			return View(model);
		}

		[HttpPost]
		public ActionResult Setup(TemplateModel model, int oldSelectedProjectId)
		{

			if (model.SelectedProjectId == oldSelectedProjectId)
			{
				return PartialView("SetupForm", model);
			}

			Project project = projectService.GetProjectById(model.SelectedProjectId);

			TemplateModel newModel = GetTempleteModel(project);

			return PartialView("SetupForm", newModel);
		}

		[HttpPost]
		public ActionResult Save(int id, string selectedFields, Separators separator)
		{
			TemplateModel model = new TemplateModel()
			{
				Separator = separator,
				SelectedFields = selectedFields
					.Split('-')
					.Select(x => Enum.Parse(typeof(AvaliableFields), x))
					.Cast<AvaliableFields>()
					.ToList(),
				SelectedProjectId = id
			};

			string template = ComposeTemplate(model);

			Project project = projectService.UpdateProjectTemplate(id, template);

			TemplateModel newModel = GetTempleteModel(project);

			return PartialView("SetupForm", newModel);
		}

		[HttpPost]
		public ActionResult RemoveField(int id, string selectedFields, Separators separator, int indexToRemove)
		{
			TemplateModel model = new TemplateModel()
			{
				Separator = separator,
				SelectedFields = selectedFields
					.Split('-')
					.Select(x => Enum.Parse(typeof(AvaliableFields), x))
					.Cast<AvaliableFields>()
					.ToList(),
				SelectedProjectId = id
			};

			model.SelectedFields.RemoveAt(indexToRemove);
			return PartialView("SetupForm", model);
		}

		[HttpPost]
		public ActionResult AddField(int id, string selectedFields, Separators separator)
		{
			var model = new TemplateModel()
			{
				Separator = separator,
				SelectedFields = selectedFields
					.Split('-')
					.Select(f => Enum.Parse(typeof(AvaliableFields), f))
					.Cast<AvaliableFields>()
					.ToList(),
				SelectedProjectId = id
			};

			model.SelectedFields.Add(model.Fields.First(f => f.IsUsed == false).Field);

			return PartialView("SetupForm", model);
		}

		private TemplateModel GetTempleteModel(Project project)
		{
			Separators separator;
			AvaliableFields[] selectedFields = projectService.GetTempleteItems(project.Template, out separator);

			var model = new TemplateModel(project.ProjectId, selectedFields, separator);

			return model;
		}

		private string ComposeTemplate(TemplateModel model)
		{
			string[] result = new[] {
				model.Separator.ToString()
			}
			.Union(model.SelectedFields.Select(x => x.ToString()))
			.ToArray();

			return string.Join(";", result);
		}
	}
}

FileTemplateManager/Controllers/UploadController.cs
using Bussiness;
using FileTemplateManager.Providers;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;
using System.Web;
using System.Web.Http;

namespace FileTemplateManager.Controllers
{
	public sealed class UploadController : ApiController
	{
		private readonly HttpContextBase httpContextBase;
		private readonly IProjectService projectService;
		private readonly IProjectMultipartFormDataStreamProviderFactory factory;

		public UploadController(
			IProjectService projectService,
			HttpContextBase httpContextBase,
			IProjectMultipartFormDataStreamProviderFactory factory
		)
		{
			this.projectService = projectService;
			this.httpContextBase = httpContextBase;
			this.factory = factory;
		}

		public async Task<HttpResponseMessage> PostFile(int id)
		{
			if (!Request.Content.IsMimeMultipartContent())
			{
				throw new HttpResponseException(HttpStatusCode.UnsupportedMediaType);
			}

			int questionId = id;
			string root = httpContextBase.Server.MapPath("~/App_Data");
			MultipartFormDataStreamProvider provider = factory.Create(questionId, root);

			try
			{
				await Request.Content.ReadAsMultipartAsync(provider);

				MultipartFileData file = provider.FileData.SingleOrDefault();
				if (file == null)
				{
					throw new HttpResponseException(HttpStatusCode.BadRequest);
				}

				FileInfo fileInfo = new FileInfo(file.LocalFileName);

				projectService.SaveAnswerByQuestion(questionId);

				return new HttpResponseMessage()
				{
					Content = new StringContent("ok")
				};
			}
			catch (Exception ex)
			{
				return Request.CreateErrorResponse(HttpStatusCode.InternalServerError, ex);
			}
		}
	}
}

FileTemplateManager/Views/Home/Index.cshtml
@{
	ViewBag.Title = "Index";
}

<div>
	<h1>Welcome to guidance!</h1>
	<p>@Html.ActionLink("Setup template", "Setup", "ManageTemplate")</p>
	<p>@Html.ActionLink("Create answer", "SetAnswer")</p>
</div>

FileTemplateManager/Views/Home/SetAnswer.cshtml
@model FileTemplateManager.Models.AnswerModel

@{
	ViewBag.Title = "SetAnswer";
}

<h2>Set Answer</h2>
<form id="form1" name="form1" method="post" enctype="multipart/form-data" action="@Url.RouteUrl("DefaultApi", new { httproute = true, controller = "Upload", id = Model.SelectedQuestion.QuestionId })">
	<table class="table table-bordered">
		<tr>
			<th>
				@Html.Label("Project", new { @class = "control-label col-md-2" })
			</th>
			<th>
				@Html.DropDownList(
					"selectedProject",
					Model.Projects
						.Select(p => new SelectListItem()
						{
							Text = p.ProjectName,
							Value = p.ProjectId.ToString(),
							Selected = Model.SelectedProject.ProjectId == p.ProjectId
						}),
					new { onchange = "selectedProjectOnChanged()", @class = "form-control" }
				)
			</th>
		</tr>
		<tr>
			<th>
				@Html.Label("Question", new { @class = "control-label col-md-2" })
			</th>
			<th>
				@Html.DropDownList(
					"selectedQuestion",
					Model.Questions
						.Select(q => new SelectListItem()
						{
							Text = q.Text,
							Value = q.QuestionId.ToString()
						}),
					new { onchange = "selectedQuestionOnChanged()", @class = "form-control" }
				)
			</th>
		</tr>
		<tr>
			<th>
				@Html.Label("Upload image", new { @class = "control-label col-md-2" })
			</th>
			<th>
				<input type="file" name="image" accept="image/*" />
			</th>
		</tr>
		<tr>
			<th colspan="3">
				<input type="submit" name="submit" value="Upload" class="btn-default btn-success" />
			</th>
		</tr>
	</table>
</form>

<script type="text/javascript">
	function selectedProjectOnChanged() {
		var projectId = $('#selectedProject').val();

		$.ajax({
			url: '/Home/GetQuestions',
			type: "GET",
			dataType: "JSON",
			data: { projectId: projectId },
			success: function (questions) {
				$("#selectedQuestion").html(""); // clear before appending new list
				$.each(questions, function (i, question) {
					$("#selectedQuestion").append(
						$('<option></option>').val(question.QuestionId).html(question.Text));
				});
			}
		});

		ReloadQuestions();
	}

	function selectedQuestionOnChanged() {
		var questionId = $('#selectedQuestion').val();
		var route = '@Url.RouteUrl("DefaultApi", new { httproute = true, controller = "Upload" }).ToString()';
		$("form").attr("action", route + "\/" + questionId);
	}
</script>

FileTemplateManager/Views/ManageTemplate/Setup.cshtml
@model FileTemplateManager.Models.TemplateModel
<h2>Setup</h2>

@using (Ajax.BeginForm("Setup", "ManageTemplate", new AjaxOptions() { HttpMethod = "POST", InsertionMode = InsertionMode.Replace, UpdateTargetId = "result" }))
{
	@Html.DropDownListFor(
		m => m.SelectedProjectId,
		Model.Projects
			.Select(x => new SelectListItem
			{
				Text = x.ProjectName,
				Value = x.ProjectId.ToString(),
				Selected = x.ProjectId == Model.SelectedProjectId
			}),
		new { onchange = "$('form').submit();",  @class = "form-control" }
	)
	<p/>

	<div id="result">
		@Html.Partial("SetupForm", Model)
	</div>
}

FileTemplateManager/Views/ManageTemplate/SetupForm.cshtml
@model FileTemplateManager.Models.TemplateModel
@using Bussiness

<input type='hidden' name='oldSelectedProjectId' value='@Model.SelectedProjectId' />

<table id="tableFields" class="table table-bordered">
	<tbody id="tableBody">
		<tr>
			<td>@Html.Label("Sample File Name", new { @class = "control-label col-md-2" })</td>
			<td colspan="2">@Html.DisplayTextFor(f => f.SampleFileName)</td>
		</tr>
		<tr>
			<th colspan="3">
				@Html.Label("Select custom fields", new { @class = "control-label col-md-2" })
			</th>
		</tr>

@{
	int i = 0;
	foreach (AvaliableFields field in Model.SelectedFields)
	{
		<tr>
			<td></td>
			<td>
				@Html.DropDownList(
					 "Select" + i,
						 Model.Fields
						 .Where(x => x.IsUsed == false || x.Field == field)
						 .Select(x => new SelectListItem
						 {
							 Text = x.Field.ToString(),
							 Value = x.Field.ToString(),
							 Selected = field == x.Field
						 }),
					 new { onchange = "$('form').submit();", Name = "SelectedFields", @class = "form-control" }
				 )
			</td>

			<td>
				@if (i != 0)
				{ 
					@Ajax.ActionLink(
						"X",
						"RemoveField",
						new {
							controller = "ManageTemplate",
							action = "RemoveField",
							id = Model.SelectedProjectId,
							Separator = Model.Separator,
							SelectedFields = String.Join("-", Model.SelectedFields.Select(x => (int)x).ToArray()),
							IndexToRemove = i
						},
						new AjaxOptions()
						{
							HttpMethod = "POST",
							InsertionMode = InsertionMode.Replace,
							UpdateTargetId = "result"
						},
						new { @class = "btn btn-default btn-danger" }
					)
				}
				@{i++;}
			</td>
		</tr>
						}

		<tr>
			<td>
				@{if (Model.Fields.Count != Model.SelectedFields.Count)
					{
						@Ajax.ActionLink(
							"+",
							"AddField",
							new {
								controller = "ManageTemplate",
								action = "AddField",
								id =Model.SelectedProjectId,
								Separator = Model.Separator,
								SelectedFields = String.Join("-", Model.SelectedFields.Select(x => (int)x).ToArray())
							},
							new AjaxOptions()
							{ HttpMethod = "POST", InsertionMode = InsertionMode.Replace, UpdateTargetId = "result" },
							new { @class = "btn btn-default btn-success" }
						)
					}
				}
			</td>
			<td></td>
			<td></td>
		</tr>

		<tr>
			<th colspan="3">
				@Html.Label("Select separator", new { @class = "control-label col-md-2" })
			</th>
		</tr>

		<tr>
			<td></td>
			<td>
				@Html.DropDownList(
					"SeparatorDropDownList",
					Enum.GetValues(typeof(Separators))
						.Cast<Separators>()
						.Select(x => new SelectListItem
						{
							Value = x.ToString(),
							Text = x.ToString(),
							Selected = x == Model.Separator
						}),
					new { onchange = "$('form').submit();", Name = "Separator", @class = "form-control" }
				)
				</td>
				<td></td>
			</tr>
		}
	</tbody>
</table>

<p>
	@Ajax.ActionLink(
		"Save",
		"Save",
		new
		{
			controller = "ManageTemplate",
			action = "Save",
			id = Model.SelectedProjectId,
			Separator = Model.Separator,
			SelectedFields = String.Join("-", Model.SelectedFields.Select(x => (int)x).ToArray())
		},
		new AjaxOptions()
		{
			HttpMethod = "POST",
			InsertionMode = InsertionMode.Replace,
			UpdateTargetId = "result"
		},
		new { @class = "btn btn-default btn-green" }
	)
</p>

FileTemplateManager/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>@ViewBag.Title </title>
	<link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
	<link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
	<script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
	<script src="~/Scripts/jquery-1.10.2.min.js"></script>
	<script src="~/Scripts/bootstrap.min.js"></script>
	<script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>

	<div class="container body-content">
		@RenderBody()
	</div>
</body>
</html>